version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./databases/mongodb:/databases/mongodb
    ports:
      - 27017:27017
  web:
    build: ./backend
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  sock:
    build: ./backend
    command: bundle exec puma -p 28080 cable/config.ru
    volumes:
      - ./backend:/backend
    ports:
      - "28080:28080"
    depends_on:
      - mongodb
