version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./databases/mongodb:/databases/mongodb
    ports:
      - 27017:27017
  redis:
    image: "redis:alpine"
    volumes:
      - './databases/redis:/databases/redis'
    ports:
      - 6379:6379
  #nginx:
  #  build: ./frontend
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - ./logs/nginx/:/var/log/nginx:cached
  #  depends_on:
  #    - web
  #    - sock
  #    - mongodb
  #    - redis
  web:
    build: ./backend
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - sock
  sock:
    build: ./backend
    command: bundle exec puma -p 28080 cable/config.ru
    volumes:
      - ./backend:/backend
    ports:
      - "28080:28080"
    depends_on:
      - mongodb
      - redis
